// Auto-generated by deploy.ts — do not edit manually.
// Re-run: cd packages/contracts && npm run deploy:local
import VeriSkillCredentialABI from './VeriSkillCredential.json'
export { VeriSkillCredentialABI }
export const CONTRACT_ADDRESS_LOCALHOST = '0x5FbDB2315678afecb367f032d93F642f64180aa3'
